name: 04-encrypt-var
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 运行04
        required: true
        default: true
        type: boolean
env:
  MY_NAME: ${{secrets.WF_ENV}}
jobs:
  log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print Environment Variables
        run: |
          echo "MY_NAME: $MY_NAME"
