name: use-strategy
on:
    workflow_dispatch:
        inputs:
        who-to-greet:
            description: 运行11
            required: true
            default: true
            type: boolean
jobs:
  use-more-node:
    strategy:
      parallel: 2  # 并行执行两个任务
      fail-fast: false  # 不要立即停止所有任务
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [21, 22, 23]
    runs-on: ${{ matrix.os }}
    steps:
      - name: print node version
        run: node -v
      - name: use node action
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: print node version
        run: node -v

