name: Actions Workflow
on:
  push
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls
      - name: Simple Js Action
        id: great
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
      - name: Log greeting Title
        run: echo "${{steps.great.outputs.time}}"
