name: Actions Workflow
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: Who to greet in the log
        required: true
        default: 'World'
        type: string

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:

      - name: list files
        run: |
          pwd
          ls -a
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Simple Js Action
        id: great
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ inputs.who-to-greet }}
      - name: Log greeting Title
        run: echo "${{steps.great.outputs.time}}"
