name: Actions Workflow
on:

  schedule:
    - cron: "0/5 * * * *" # every 5 minutes
  pull_request:
    types: [closed,assigned,opened,reopened]
#  workflow_dispatch:
#    inputs:
#      who-to-greet:
#        description: Who to greet in the log
#        required: true
#        default: 'World'
#        type: string

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
#          git clone git@github:@GITHUB_REPOSITORY
#          git checkout $GITHUB_SHA
      - name: Checkout
        uses: actions/checkout@v4
      - name: List files after checkout
        run: |
          pwd
          ls -a
#      - name: Simple Js Action
#        id: great
#        uses: actions/hello-world-javascript-action@main
#        with:
#          who-to-greet: ${{ inputs.who-to-greet }}
      - name: Log greeting Title
        run: echo "${{steps.great.outputs.time}}"
