name: Shell Command
on:
  [push]
jobs:
  run_shell_command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: eccho "Hello, World! github actions"
      - name: multi-line shell command
        run: |
          node -v
          npm -v
      
        
